trigger: none

pool:
  vmImage: 'windows-latest'

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '10.x'

- script: dotnet restore
  displayName: Restore

- script: dotnet publish EmployeeManagementAPI/EmployeeManagementAPI.csproj -c Release -o $(Build.ArtifactStagingDirectory)/api
  displayName: Publish API

- task: AzureWebApp@1
  displayName: Deploy API

  inputs:
    azureSubscription: 'EmployeeManagement-Azure-Connection'
    appType: 'webApp'
    appName: 'employeemanagementapi-libitha-dev'
    package: '$(Build.ArtifactStagingDirectory)/api'
