trigger: none

pool:
  vmImage: 'windows-latest'

stages:
- stage: DeployDevelopment

  jobs:
  - deployment: DeployAPI

    environment: Development

    strategy:
      runOnce:
        deploy:
          steps:

          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'EmployeeManagement-Azure-Connection'
              appType: 'webApp'
              appName: 'employeemanagementapi-libitha-dev'
              package: '$(Build.ArtifactStagingDirectory)'
