trigger: none

pool:
  vmImage: 'windows-latest'

stages:
- stage: DeployDevelopment
  displayName: Deploy to Development

  jobs:
  - deployment: DeployAPI
    displayName: Deploy API
    environment: Development

    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Deploying API
            displayName: Test Deployment