# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - employeemanagementapi-libitha-dev

on:
  push:
    branches:
      - feature/github-actions
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Build API
        run: dotnet build EmployeeManagementAPI/EmployeeManagementAPI.csproj --configuration Release

      - name: Publish API
        run: dotnet publish EmployeeManagementAPI/EmployeeManagementAPI.csproj --configuration Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_493F2BFC32214D53B0B4472CB4333DAE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5B5CF215411B4FCA97D92E1D1B2BB91B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CB6298CDBCD349AEA4DD2E7A08D591DC }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'employeemanagementapi-libitha-dev'
          slot-name: 'Production'
          package: .
          